Module - 1: Capstone Project - WOS Concert Webpage
tan12082001/Project-Capstone-1 pull request #1
Opened 2023-06-28 18:28 UTC by tan12082001

Microverse Module - 1, week - 5: Capstone project
Project: HTML/CSS & JavaScript capstone project - Conference page.
As it is up to the choice of Micronauts to select the topic of the webpage, I choose to do a Concert Page.
Project Requirements achieved:
*  Personalize the content of your page
*  following the design guidelines for font sizes, colours, font face and layout.
* Build two web pages:

1.  Home Page
2.  About page

* To have a Responsive webpage with breakpoints for the mobile version and desktop version.
* home page should have a link in the menu to the About page
* logo in the header links to the home page.
* Mobile version should have a hamburger button and a popup of navigation elements.
* The section "Featured Artists" should be created dynamically in JavaScript.

2023-06-28 19:06 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @tan12082001 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️ Speakers are created dynamically
✔️content is personalized
✔️style almost looks identical
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 19:06 UTC, tugsem commented on main.css
> +
- [x] Kindly remove the logo from the mobile version of the app to match the design.

2023-06-28 19:06 UTC, tugsem commented on main.css
> +}
- [x] Kindly set your header's background color to transparent, remove the logo, and add weight to your hamburger icon to match this design:
yours: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/e406a990-e199-48c3-9535-6171bf5ccf22)
given:
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/2ceac43e-eb77-4309-ac30-c6aff5176818)

2023-06-28 19:06 UTC, tugsem commented on main.css
> +  color: #333;
- [x] Kindly set your font color to this value as in the given design which is #272A31: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/91773b85-5d84-4501-bb79-e50088317b0c)

2023-06-28 19:06 UTC, tugsem commented on about.css
> +}
- [x] Kindly remove the margins at the sides, the background image should cover the page and the header as in the given design. :
yours: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/096cdaa4-89a3-431d-9bf4-9adbc7559897)
given: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/12e9d3bd-8f74-465f-8c92-88e94e64d9d5)

2023-06-28 19:06 UTC, tugsem commented on about.css
> +}
- [x] Kindly center this div horizontally and set its border color to light grey to match the given design I attached the images above.

2023-06-28 19:06 UTC, tugsem commented on about.css
> +  color: #333;
- [x] The font color should be the same as in the main.css which should be #272A31 to match the given design.

2023-06-28 19:06 UTC, tugsem commented on main.css
> +  -webkit-text-fill-color: transparent;
- [ ] On the main page, these main titles should be aligned to the left. Also, your h1 title should be written in the uppercase. Kindly fix it to match the given design: 
yours: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/c31e42d5-d56a-4ce7-8fae-4f0fdcc5edf3)
given:
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/5799f87f-c2b3-4289-ab6c-d5dccdbb1e51)

2023-06-28 19:06 UTC, tugsem commented on main.css
> +  }
- [ ] Please add spacing to the right of this div to match the given design layout:
yours:
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/f8d8720e-7357-4f5f-8009-f88b0cd6c897)
given: 
![image](https://github.com/tan12082001/Project-Capstone-1/assets/91486791/db4738b8-fe53-469b-9ac3-bbc1e74484fc)

2023-06-29 12:23 UTC, mckent05 approved these changes
Hi @tan12082001 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 
- You have done well completing your first capstone project, keep going 🚀 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 12:23 UTC, mckent05 commented on index.html
> +                        </ul>
**OPTIONAL** - You did well wrapping this section in a `ul` tag, but to help improve the semantics of your page, please wrap each `a` tag in a corresponding `li` tag. Please fix this for both pages 🙏

2023-06-29 12:23 UTC, mckent05 commented on index.html
> +                </nav>
**OPTIONAL** - It is not advisable to have two `nav` tags on one HTML page, I suggest you have just one nav tag, then use CSS to customize the nav for either the mobile or desktop version. Please fix this for both pages 🙏

2023-06-29 12:23 UTC, mckent05 commented on index.html
> +                <h1 class="headline-h1">White Orange Sky Summer Concert 2023</h1>
**OPTIONAL** - You have done well so far, but to help improve the semantics of your page, it is advisable to let your `hx` tag follow an ascending hierarchy, i.e use an `h2`tag after an `h1` tag, use an `h3` tag after an `h2` tag e.t.c. Please fix this 🙏

2023-06-29 12:29 UTC, merged